name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: .
      - name: Print working directory
        run: pwd && ls -al && tree || true
        working-directory: ${{ github.workspace }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}
      - name: Run ESLint
        run: npm run lint
        working-directory: ${{ github.workspace }}
      - name: Check Prettier formatting
        run: npx prettier --check .
        working-directory: ${{ github.workspace }}
